export const WOLF_QUOTES = [
  "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
  "Winners use words that say 'must' and 'will'.",
  "Act as if! Act as if you're a wealthy man, rich already, and you will become rich.",
  "The easiest way to make money is to create something of such value that everybody wants and go out and give and create value.",
  "There is no nobility in poverty.",
  "I've been a poor man, and I've been a rich man. And I choose rich every time.",
  "Let me tell you something. There's no nobility in poverty.",
  "I want you to deal with your problems by becoming rich!",
  "The only thing standing between you and your goal is the bullshit story you keep telling yourself.",
  "Fall in love with the process and the results will come.",
  "If you want to be rich, never give up. People tend to give up.",
  "Without action, the best intentions in the world are nothing more than that: intentions.",
  "When you live your life by poor standards, you inflict damage on everyone who crosses your path.",
  "The wolf is always at the door. It's up to you to invite him in or keep him out.",
  "Successful people are 100% convinced that they are masters of their own destiny.",
  "Don't let anyone, ANYONE, tell you that you can't do something.",
  "Every person around here, they want to get rich, day one.",
  "Money is the oxygen of capitalism and I wanna breathe more than any man alive.",
  "You gotta pump those numbers up. Those are rookie numbers.",
  "I'm not gonna die sober!",
  "Sell me this pen.",
  "There's two keys to success in any business. Number one is revenue. Number two is revenue.",
  "The real question is this: Was all this legal? Absolutely not.",
  "Risk is what prevents people from living their dreams.",
  "I believe in total immersion, if you want to be rich, you have to program your mind to be rich.",
  "Hard work beats talent when talent doesn't work hard.",
  "The name of the game: moving money from your client's pocket to your pocket.",
  "Give them to me young, hungry, and stupid. And in no time, I will make them rich.",
  "On a daily basis I consume enough drugs to sedate Manhattan.",
  "It's business. Leave your emotions at the door.",
  "Stratton Oakmont is America!",
  "Number one rule of Wall Street. Nobody... I don't care if you're Warren Buffett or if you're Jimmy Buffett. Nobody knows if a stock is gonna go up, down, sideways or in circles.",
  "Best way to sell something: don't sell anything. Earn awareness, respect, and trust of those who might buy.",
  "Every sale has five basic obstacles: no need, no money, no hurry, no desire, no trust.",
  "You want a friend? Get a dog.",
  "The wolf on the hill is never as hungry as the wolf climbing the hill.",
  "Power doesn't corrupt. It reveals.",
  "When the window of opportunity opens, you gotta be ready to jump through it.",
  "My warriors who knock on doors. Who won't take no for an answer!",
  "I want you to back yourself into a corner. Give yourself no choice but to succeed.",
  "People don't buy what you do, they buy why you do it.",
  "One thing I can promise you is that I never ask my clients to judge me on my winners. I ask them to judge me on my losers.",
  "Relentless. That's the word. Relentless.",
  "Every morning I get up, I check the markets before I even brush my teeth.",
  "Pick up the phone and start dialing!",
  "The telephone is your best friend and your worst enemy.",
  "I need you to solve your problems by getting rich!",
  "If you can make a client money, you can make yourself money.",
  "The revolution will not be satisfying your need for instant gratification.",
  "Do you know what a fugazi is? It's a fake. It's a whazy. It's a woozy."
]

export function getRandomQuote(): string {
  return WOLF_QUOTES[Math.floor(Math.random() * WOLF_QUOTES.length)]
}
